const SET_AUTH = "SET_AUTH";
const SET_SUBSCRIBER = "SET_SUBSCRIBER_AUTH";
const SET_LOADING = "SET_LOADING";
const SET_LOADING_FORM = "SET_LOADING_FORM";
const SET_ERROR = "SET_ERROR";

export {
  SET_AUTH,
  SET_LOADING,
  SET_LOADING_FORM,
  SET_ERROR,
  SET_SUBSCRIBER
};
