const SET_ALL = "SET_ALL_CATEGORIES_PRODUCTS";
const SET_ONE = "SET_ONE_CATEGORIES_PRODUCTS";
const SET_LOADING = "SET_LOADING_CATEGORIES_PRODUCTS";
const SET_ERROR = "SET_ERROR_CATEGORIES_PRODUCTS";

export {
  SET_ALL,
  SET_ONE,
  SET_LOADING,
  SET_ERROR
};
