const SET_ALL = "SET_ALL_CATEGORIES";
const SET_LOADING = "SET_LOADING_CATEGORIES";
const SET_ERROR = "SET_ERROR_CATEGORIES";
const SET_CREATED = "SET_CREATED_CATEGORIES";
const SET_DELETED = "SET_DELETED_CATEGORIES";

export {
  SET_ALL,
  SET_CREATED,
  SET_DELETED,
  SET_LOADING,
  SET_ERROR
};
