const SET_ALL = "SET_ALL_PRODUCTS";
const SET_ONE = "SET_ONE_PRODUCTS";
const SET_SELECTED = "SET_SELECTED_PRODUCTS";
const SET_LOADING = "SET_LOADING_PRODUCTS";
const SET_ERROR = "SET_ERROR_PRODUCTS";
const SET_SOURCES = "SET_SOURCES_PRODUCTS";

export {
  SET_ALL,
  SET_ONE,
  SET_SELECTED,
  SET_LOADING,
  SET_ERROR,
  SET_SOURCES
};
